name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install
        env:
          POETRY_HTTP_BASIC_TESTPYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_TESTPYPI_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Test with pytest
        run: poetry run pytest tests/ -q
